using UnityEngine;
using UnityEngine.UI;

namespace AdamFolder.Scripts
{
    public class Timer : MonoBehaviour
    {
        public float timeRemaining = 10;
        public bool timerIsRunning = false;
        public Text timeText;
    
        private void Start()
        {
            timerIsRunning = true;
        }

        void Update()
        {
            if (timerIsRunning)
            {
                if (timeRemaining > 0)
                {
                    timeRemaining -= Time.deltaTime;
                }
                else
                {
                    Debug.Log("Time has run out!");
                    timeRemaining = 0;
                    timerIsRunning = false;
                }
            }
        }

        void DisplayTime(float timeToDisplay)
        {
            timeToDisplay +=1;
            float minutes = Mathf.FloorToInt(timeToDisplay /60);
            float seconds = Mathf.FloorToInt(timeToDisplay % 60);
            timeText.text = string.Format("{0:00}:{1:00}", minutes, seconds);
        }
    }
}